spring:
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/demo?allowMultiQueries=true&useSSL=false
    username: root
    password: root@123
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy