spring:
  datasource:
    url: jdbc:log4jdbc:mysql://47.104.200.143:7306/demo?allowMultiQueries=true&useSSL=false
    username: root
    password: d2FuZ2pnMDcyNA==
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy